### ISSUE TITLE
 Failed at the @ start script 'node ./build/src/runtime/server.js "server"'.

### ISSUE THREAD

**Issue by fpessolano** [witheve/Eve#563]
I just downloaded the latest git and when I start the servers it reports error. This is the full transcript

```
fpex:Eve-master francescopessolano$ npm start server

> @ start /Users/francescopessolano/Desktop/work_folder_synced/coding/Eve-master
> node ./build/src/runtime/server.js "server"

module.js:474
    throw err;
    ^

Error: Cannot find module '/Users/francescopessolano/Desktop/work_folder_synced/coding/Eve-master/build/src/runtime/server.js'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "server"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ start: `node ./build/src/runtime/server.js "server"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'node ./build/src/runtime/server.js "server"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build/src/runtime/server.js "server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/francescopessolano/Desktop/work_folder_synced/coding/Eve-master/npm-debug.log
```

**Comment by olafleur** [comment]
Could you give us what you did to solve your issue? It would probably be helpful if somebody else has this problem.

**Comment by fpessolano** [comment]
I agree it would .... except I simply made a silly error to forget npm install :-)

-----
Sent by My IPhone6
