### ISSUE TITLE
Bad @http code causes the server to crash.

### ISSUE THREAD

**Issue by Cormac-Williams** [witheve/Eve#668]
Playing with the code from another issue I found bad @http code added to quickstart.eve causes the server to crash.

If you add this to the quickstart.eve

commit @http
   [#request #get-all url: "http://localhost:8081/getAll"]

Stop and start the server, possibly do npm install again (I was playing with a couple of things.)
Make the request to localhost:8080.

Server stops with the message

/home/noiwont/src/Eve/build/src/runtime/server.js:280
            throw err;
                  ^
TypeError: Cannot read property 'headers' of undefined
    at Request._callback (/home/noiwont/src/Eve/build/src/runtime/databases/node/http.js:50:25)
    at self.callback (/home/noiwont/src/Eve/node_modules/request/request.js:186:22)
    at Request.EventEmitter.emit (events.js:95:17)
    at Request.onRequestError (/home/noiwont/src/Eve/node_modules/request/request.js:845:8)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)

I wasn't running anything on 8081 and was expecting the record to reflect the issue.

Also seems to be running in the node version of @http, so I'm assuming the code got compiled in and then runs on the server side rather than client side.

Regards,
Cormac.

**Comment by ibdknox** [comment]
So I believe the issue that caused the code to run on the server as well has been fixed, but we were also not bailing in the case of http errors. That's fixed in my PR. @convolvatron is going to follow up with another PR as well that makes the errors actionable on the Eve side.
