### ISSUE TITLE
the thing that is supposed to have a providers element isn't defined

### ISSUE THREAD

**Issue by convolvatron** [witheve/Eve#678]
TypeError: Cannot read property 'providers' of undefined
   at stratify (/Users/erichoffman/Eve/build/src/runtime/builder.js:703:51)
   at buildStrata (/Users/erichoffman/Eve/build/src/runtime/builder.js:764:18)
   at buildBlock (/Users/erichoffman/Eve/build/src/runtime/builder.js:772:14)
   at Object.buildDoc (/Users/erichoffman/Eve/build/src/runtime/builder.js:804:18)
   at HTTPRuntimeClient.RuntimeClient.makeEvaluation (/Users/erichoffman/Eve/build/src/runtime/runtimeClient.js:38:29)
   at HTTPRuntimeClient.RuntimeClient.load (/Users/erichoffman/Eve/build/src/runtime/runtimeClient.js:28:14)
   at /Users/erichoffman/Eve/build/src/runtime/server.js:112:20
   at Layer.handle [as handle_request] (/Users/erichoffman/Eve/node_modules/express/lib/router/layer.js:95:5)
   at next (/Users/erichoffman/Eve/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/erichoffman/Eve/node_modules/express/lib/router/route.js:112:3)

**Comment by convolvatron** [comment]
fixed on master
