### ISSUE TITLE
Nodes that are neither values nor constants used in `else` branch break editor

### ISSUE THREAD

**Issue by cmontella** [witheve/Eve#694]
Loading the following program causes the editor to fail to load with the error:

> chevrotain.js:1277 Uncaught Error: Tried to get value of a node that is neither a constant nor a variable.(…)

https://gist.github.com/anonymous/e843fa852d674407947bb6693c7e0dab

**Comment by cmontella** [comment]
When I found this bug, it caused the server to crash with the following dump:

```
Error: Tried to get value of a node that is neither a constant nor a variable.

{"entity":{"id":"view|block|16|sub11|node|0","type":"variable","name":"wrapper","from":[{"image":"wrapper","startOffset":1863,"startLine":4,"startColumn":30,"endLine":4,"endColumn":36,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|24"}],"generated":false,"startOffset":1863,"endOffset":1870},"attribute":{"value":"tag","from":[{"image":"tag","startOffset":1884,"startLine":4,"startColumn":51,"endLine":4,"endColumn":53,"isInsertedInRecovery":false,"label":"string","id":"view|block|16|token|28"}],"id":"view|block|16|sub11|node|2","startOffset":1884,"endOffset":1887,"type":"constant"},"value":{"value":"attribute-table","from":[{"image":"attribute-table","startOffset":1898,"startLine":4,"startColumn":65,"endLine":4,"endColumn":79,"isInsertedInRecovery":false,"label":"string","id":"view|block|16|token|33"}],"id":"view|block|16|sub11|node|4","startOffset":1898,"endOffset":1913,"type":"constant"},"node":{"id":"view|block|16|node|8","type":"variable","name":"node","from":[{"image":"node","startOffset":1916,"startLine":4,"startColumn":83,"endLine":4,"endColumn":86,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|35"}],"generated":false,"startOffset":1916,"endOffset":1920},"scopes":["view"],"from":[{"image":"lookup","startOffset":1848,"startLine":4,"startColumn":15,"endLine":4,"endColumn":20,"isInsertedInRecovery":false,"label":"lookup","id":"view|block|16|token|20"},{"attributes":[{"attribute":"record","value":{"id":"view|block|16|sub11|node|0","type":"variable","name":"wrapper","from":[{"image":"wrapper","startOffset":1863,"startLine":4,"startColumn":30,"endLine":4,"endColumn":36,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|24"}],"generated":false,"startOffset":1863,"endOffset":1870},"from":[{"image":"record","startOffset":1855,"startLine":4,"startColumn":22,"endLine":4,"endColumn":27,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|22"},{"image":":","startOffset":1861,"startLine":4,"startColumn":28,"endLine":4,"endColumn":28,"isInsertedInRecovery":false,"label":"equality","id":"view|block|16|token|23"},{"id":"view|block|16|sub11|node|0","type":"variable","name":"wrapper","from":[{"image":"wrapper","startOffset":1863,"startLine":4,"startColumn":30,"endLine":4,"endColumn":36,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|24"}],"generated":false,"startOffset":1863,"endOffset":1870}],"id":"view|block|16|sub11|node|1","startOffset":1855,"endOffset":1870,"type":"attribute","nonProjecting":false},{"attribute":"attribute","value":{"value":"tag","from":[{"image":"tag","startOffset":1884,"startLine":4,"startColumn":51,"endLine":4,"endColumn":53,"isInsertedInRecovery":false,"label":"string","id":"view|block|16|token|28"}],"id":"view|block|16|sub11|node|2","startOffset":1884,"endOffset":1887,"type":"constant"},"from":[{"image":"attribute","startOffset":1872,"startLine":4,"startColumn":39,"endLine":4,"endColumn":47,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|25"},{"image":":","startOffset":1881,"startLine":4,"startColumn":48,"endLine":4,"endColumn":48,"isInsertedInRecovery":false,"label":"equality","id":"view|block|16|token|26"},{"value":"tag","from":[{"image":"tag","startOffset":1884,"startLine":4,"startColumn":51,"endLine":4,"endColumn":53,"isInsertedInRecovery":false,"label":"string","id":"view|block|16|token|28"}],"id":"view|block|16|sub11|node|2","startOffset":1884,"endOffset":1887,"type":"constant"}],"id":"view|block|16|sub11|node|3","startOffset":1872,"endOffset":1887,"type":"attribute","nonProjecting":false},{"attribute":"value","value":{"value":"attribute-table","from":[{"image":"attribute-table","startOffset":1898,"startLine":4,"startColumn":65,"endLine":4,"endColumn":79,"isInsertedInRecovery":false,"label":"string","id":"view|block|16|token|33"}],"id":"view|block|16|sub11|node|4","startOffset":1898,"endOffset":1913,"type":"constant"},"from":[{"image":"value","startOffset":1890,"startLine":4,"startColumn":57,"endLine":4,"endColumn":61,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|30"},{"image":":","startOffset":1895,"startLine":4,"startColumn":62,"endLine":4,"endColumn":62,"isInsertedInRecovery":false,"label":"equality","id":"view|block|16|token|31"},{"value":"attribute-table","from":[{"image":"attribute-table","startOffset":1898,"startLine":4,"startColumn":65,"endLine":4,"endColumn":79,"isInsertedInRecovery":false,"label":"string","id":"view|block|16|token|33"}],"id":"view|block|16|sub11|node|4","startOffset":1898,"endOffset":1913,"type":"constant"}],"id":"view|block|16|sub11|node|5","startOffset":1890,"endOffset":1913,"type":"attribute","nonProjecting":false},{"attribute":"node","value":{"id":"view|block|16|node|8","type":"variable","name":"node","from":[{"image":"node","startOffset":1916,"startLine":4,"startColumn":83,"endLine":4,"endColumn":86,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|35"}],"generated":false,"startOffset":1916,"endOffset":1920},"from":[{"id":"view|block|16|node|8","type":"variable","name":"node","from":[{"image":"node","startOffset":1916,"startLine":4,"startColumn":83,"endLine":4,"endColumn":86,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|35"}],"generated":false,"startOffset":1916,"endOffset":1920}],"id":"view|block|16|sub11|node|6","startOffset":1916,"endOffset":1920,"type":"attribute","nonProjecting":false}],"action":false,"scopes":["view"],"from":[{"image":"[","startOffset":1854,"startLine":4,"startColumn":21,"endLine":4,"endColumn":21,"isInsertedInRecovery":false,"label":"open-bracket","id":"view|block|16|token|21"},{"attribute":"record","value":{"id":"view|block|16|sub11|node|0","type":"variable","name":"wrapper","from":[{"image":"wrapper","startOffset":1863,"startLine":4,"startColumn":30,"endLine":4,"endColumn":36,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|24"}],"generated":false,"startOffset":1863,"endOffset":1870},"from":[{"image":"record","startOffset":1855,"startLine":4,"startColumn":22,"endLine":4,"endColumn":27,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|22"},{"image":":","startOffset":1861,"startLine":4,"startColumn":28,"endLine":4,"endColumn":28,"isInsertedInRecovery":false,"label":"equality","id":"view|block|16|token|23"},{"id":"view|block|16|sub11|node|0","type":"variable","name":"wrapper","from":[{"image":"wrapper","startOffset":1863,"startLine":4,"startColumn":30,"endLine":4,"endColumn":36,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|24"}],"generated":false,"startOffset":1863,"endOffset":1870}],"id":"view|block|16|sub11|node|1","startOffset":1855,"endOffset":1870,"type":"attribute","nonProjecting":false},{"attribute":"attribute","value":{"value":"tag","from":[{"image":"tag","startOffset":1884,"startLine":4,"startColumn":51,"endLine":4,"endColumn":53,"isInsertedInRecovery":false,"label":"string","id":"view|block|16|token|28"}],"id":"view|block|16|sub11|node|2","startOffset":1884,"endOffset":1887,"type":"constant"},"from":[{"image":"attribute","startOffset":1872,"startLine":4,"startColumn":39,"endLine":4,"endColumn":47,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|25"},{"image":":","startOffset":1881,"startLine":4,"startColumn":48,"endLine":4,"endColumn":48,"isInsertedInRecovery":false,"label":"equality","id":"view|block|16|token|26"},{"value":"tag","from":[{"image":"tag","startOffset":1884,"startLine":4,"startColumn":51,"endLine":4,"endColumn":53,"isInsertedInRecovery":false,"label":"string","id":"view|block|16|token|28"}],"id":"view|block|16|sub11|node|2","startOffset":1884,"endOffset":1887,"type":"constant"}],"id":"view|block|16|sub11|node|3","startOffset":1872,"endOffset":1887,"type":"attribute","nonProjecting":false},{"attribute":"value","value":{"value":"attribute-table","from":[{"image":"attribute-table","startOffset":1898,"startLine":4,"startColumn":65,"endLine":4,"endColumn":79,"isInsertedInRecovery":false,"label":"string","id":"view|block|16|token|33"}],"id":"view|block|16|sub11|node|4","startOffset":1898,"endOffset":1913,"type":"constant"},"from":[{"image":"value","startOffset":1890,"startLine":4,"startColumn":57,"endLine":4,"endColumn":61,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|30"},{"image":":","startOffset":1895,"startLine":4,"startColumn":62,"endLine":4,"endColumn":62,"isInsertedInRecovery":false,"label":"equality","id":"view|block|16|token|31"},{"value":"attribute-table","from":[{"image":"attribute-table","startOffset":1898,"startLine":4,"startColumn":65,"endLine":4,"endColumn":79,"isInsertedInRecovery":false,"label":"string","id":"view|block|16|token|33"}],"id":"view|block|16|sub11|node|4","startOffset":1898,"endOffset":1913,"type":"constant"}],"id":"view|block|16|sub11|node|5","startOffset":1890,"endOffset":1913,"type":"attribute","nonProjecting":false},{"attribute":"node","value":{"id":"view|block|16|node|8","type":"variable","name":"node","from":[{"image":"node","startOffset":1916,"startLine":4,"startColumn":83,"endLine":4,"endColumn":86,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|35"}],"generated":false,"startOffset":1916,"endOffset":1920},"from":[{"id":"view|block|16|node|8","type":"variable","name":"node","from":[{"image":"node","startOffset":1916,"startLine":4,"startColumn":83,"endLine":4,"endColumn":86,"isInsertedInRecovery":false,"label":"identifier","id":"view|block|16|token|35"}],"generated":false,"startOffset":1916,"endOffset":1920}],"id":"view|block|16|sub11|node|6","startOffset":1916,"endOffset":1920,"type":"attribute","nonProjecting":false},{"image":"]","startOffset":1920,"startLine":4,"startColumn":87,"endLine":4,"endColumn":87,"isInsertedInRecovery":false,"label":"close-bracket","id":"view|block|16|token|36"}],"id":"view|block|16|sub11|node|7","startOffset":1854,"endOffset":1921,"type":"record"}],"id":"view|block|16|sub11|node|8","startOffset":1848,"endOffset":1921,"type":"scan"}
    at asValue (C:\Users\Corey\Desktop\Eve\build\src\runtime\parser.js:649:19)
    at ifOutputs (C:\Users\Corey\Desktop\Eve\build\src\runtime\parser.js:660:30)
    at Parser.<anonymous> (C:\Users\Corey\Desktop\Eve\build\src\runtime\parser.js:1389:66)
    at Parser.invokeRuleNoTry (C:\Users\Corey\Desktop\Eve\node_modules\chevrotain\lib\src\parse\parser_public.js:1093:31)
    at Parser.wrappedGrammarRule [as elseBranch] (C:\Users\Corey\Desktop\Eve\node_modules\chevrotain\lib\src\parse\parser_public.js:1159:40)
    at Parser.SUBRULE1 (C:\Users\Corey\Desktop\Eve\node_modules\chevrotain\lib\src\parse\parser_public.js:465:27)
    at Parser.SUBRULE (C:\Users\Corey\Desktop\Eve\node_modules\chevrotain\lib\src\parse\parser_public.js:443:21)
    at Parser.<anonymous> (C:\Users\Corey\Desktop\Eve\build\src\runtime\parser.js:1338:36)
    at Parser.optionInternal (C:\Users\Corey\Desktop\Eve\node_modules\chevrotain\lib\src\parse\parser_public.js:1391:20)
    at Parser.OPTION1 (C:\Users\Corey\Desktop\Eve\node_modules\chevrotain\lib\src\parse\parser_public.js:524:21)

npm ERR! Windows_NT 10.0.14965
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Corey\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! witheve@0.2.3 start: `tsc && node ./bin/eve.js`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the witheve@0.2.3 start script 'tsc && node ./bin/eve.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the witheve package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && node ./bin/eve.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs witheve
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls witheve
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Corey\Desktop\Eve\npm-debug.log
```

At the time I was modifying the @view code, but I can't seem to reproduce the crash.

**Comment by ibdknox** [comment]
This is a variant of #661

**Comment by cmontella** [comment]
Okay, then I think we can close this issue and it will be tracked there.
